services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA="Y"
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - 1434:1433
    restart: unless-stopped